---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    login_cmd_template: 'sshpass -p {password} ssh -p {port} {user}@{address}'
lint: |
  set -e
  ansible-lint
  flake8
platforms:
  - name: macos
    port: 50922
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    sudo: true
