---
- name: Check if restic is installed
  stat:
    path: '{{ restic_path }}'
  register: restic_binary

- include_tasks: install.yml
  when: not restic_binary.stat.exists

- include_tasks: configure.yml
  when: (restic_folders or restic_stdouts) and restic_repositories
