---

- name: Add systemd service for restic failure
  ansible.builtin.template:
    src: restic-backup-failure.service.j2
    dest: /etc/systemd/system/restic-backup-failure.service
    mode: u=rw,g=r,o=r
  notify: Reload systemd

- name: Add systemd service for restic
  ansible.builtin.template:
    src: restic-backup.service.j2
    dest: /etc/systemd/system/restic-backup.service
    mode: u=rw,g=r,o=r
  notify: Reload systemd

- name: Add systemd timer for restic
  ansible.builtin.template:
    src: restic-backup.timer.j2
    dest: /etc/systemd/system/restic-backup.timer
    mode: u=rw,g=r,o=r
  notify: Reload systemd

- name: Enable and start restic timer
  ansible.builtin.systemd:
    name: restic-backup.timer
    enabled: true
    state: started
