---
scenario:
  name: default
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint
  flake8
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    sudo: true
